name: french_fry
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0-rc.1
  dio: ^3.0.9
  bflutter: ^0.1.8+4
  firebase_auth: ^0.16.0
  event_bus: ^1.1.1
  page_transition: ^1.1.5
  image_picker: ^0.6.5+1
  firebase_storage: ^3.1.5
  screenshot: ^0.1.1
  flutter_sidekick: ^0.1.3
  google_maps_flutter: ^0.5.26+4
  intl: ^0.16.0
  geolocator: ^5.3.1
  rxdart: ^0.22.6
  flutter_spinkit: any
  qr: any
  contacts_service: ^0.4.6
  custom_switch_button: any
  card_selector: ^0.1.0
  smooth_star_rating: ^1.0.4+2
  qrcode: any
  toast: any
  firebase_database: any
  image_crop: ^0.3.2
  flutter_staggered_animations: any
  keyboard_attachable: any
  cloud_firestore: any
  flutter_sms: ^0.0.3
  url_launcher: ^5.4.7
  firebase_messaging: any
  shared_preferences: ^0.5.6
  flutter_local_notifications: ^1.4.4+1
  # animation lib
  supercharged: ^1.6.0
  flutter_sequence_animation: ^3.0.1
  # easy_permission_validator: ^2.0.0

  shimmer: ^1.1.1
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  image_path: "assets/base/icons/app_icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path_android: "assets/base/icons/app_icon.png"
  image_path_ios: "assets/base/icons/app_icon.png"
  adaptive_icon_background: "assets/base/icons/app_icon_adaptive.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/base/icons/app_icon_adaptive.png" # only available for Android 8.0 devices and above
# To Generate icon
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/base/icons/
    - assets/base/fonts/
    - assets/app/icons/
    - assets/app/fonts/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/base/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/base/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/base/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/base/fonts/Poppins-Semibold.ttf
          weight: 600
        - asset: assets/base/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/base/fonts/Poppins-Black.ttf
          weight: 800
    - family: SFProText
      fonts:
        - asset: assets/base/fonts/SFProText-Light.ttf
          weight: 300
        - asset: assets/base/fonts/SFProText-Regular.ttf
          weight: 400
        - asset: assets/base/fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/base/fonts/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/base/fonts/SFProText-Bold.ttf
          weight: 700
    - family: AvenirNextLTPro-Regular
      fonts:
        - asset: assets/base/fonts/AvenirNextLTPro-Regular.otf
    - family: AvenirNextLTPro-Demi
      fonts:
        - asset: assets/base/fonts/AvenirNextLTPro-Demi.otf
    - family: AvenirNextLTPro-Bold
      fonts:
        - asset: assets/base/fonts/AvenirNextLTPro-Bold.otf
